title: "Henry²"
author: "Henry Díaz Bordón"
description: "Un pequeño blog en castellano en el que hablamos sobre matemáticas y programación principalmente."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "h3nry.d1az.b0rdon@gmail.com"
#twitter_username: "twitteruser"
github_username: "h3nry-d1az"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
youtube_username: "H3nry D1az"
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: pages-themes/hacker@v0.2.0

timezone: Etc/UTC
future: false

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
