site_name: Henry Díaz Bordón
site_url: https://h3nry-d1az.github.io/
repo_url: https://github.com/h3nry-d1az/h3nry-d1az.github.io

site_description: Yet another nerdy blog about computer science and math gobbledygook
site_author: Henry Díaz Bordón
copyright: © 2024 All Rights Reserved.

theme:
  name: bootstrap386
  custom_dir: theme/
  locale: en
  logo: assets/logo.png

nav:
  - Home: index.md
  - About: about.md
  - Posts:
    - Example 1: posts/example.md

markdown_extensions:
  codehilite:
    guess_lang: true
    use_pygments: true