site_name: Henry Díaz Bordón
site_url: https://h3nry-d1az.github.io/
repo_url: https://github.com/h3nry-d1az/h3nry-d1az.github.io

site_description: Yet another nerdy blog about computer science and math gobbledygook
site_author: Henry Díaz Bordón
copyright: © 2025 All Rights Reserved.

theme:
  name: mkdocs
  custom_dir: theme/
  locale: en
  logo: assets/logo.png

nav:
  - Home: index.md
  - About: about.md
  - Publications: publications.md
  - Posts: posts/index.md

markdown_extensions:
  codehilite:
    guess_lang: true
    use_pygments: true